In [2]:
import math

In [3]:
math.ceil(4.78)

5

my_array = [[1,2,3],[4,5,6],7,8,9]]


In [4]:
print(my_array)

NameError: name 'my_array' is not defined

In [12]:
import numpy as np


In [13]:
my_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
element = my_array[0][1]

In [15]:
print(element)

2


In [17]:
element = my_array[1][0]

In [18]:
print(element)

4
