In [21]:
import numpy as np


In [31]:
A = np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])
print(A)

[[ 1 -2 -1]
 [ 2  2 -1]
 [-1 -1  2]]


In [37]:
b = np.array([6,1,1])

In [38]:
z = np.linalg.solve(A,b)

In [39]:
print(z)

[ 3. -2.  1.]
