In [6]:
A = np.arange(6).reshape(3,2)
B= np.arange(6).reshape(2,3)

In [5]:
import numpy as np

In [7]:
print(A)

[[0 1]
 [2 3]
 [4 5]]


In [8]:
print(B)

[[0 1 2]
 [3 4 5]]


In [9]:
np.matmul(A,B)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])