In [5]:
#Generate a 3x4 matrix and transpose the matrix .
import numpy as np

In [6]:
A = np.arange(12).reshape(3,4)

In [7]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])